version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  auth-service:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - db
